services:
  back:
    build: ./Back-end
    container_name: livraria-back
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mongodb+srv://victor:serverfit@livros.kmtdp0t.mongodb.net/Livros?appName=Livros
    networks:
      - app-network

  front:
    build: ./Front-end/biblioteca
    container_name: livraria-front
    ports:
      - "80:80"
    depends_on:
      - back
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
